<?php
	/* Configuration du jeu */

    define('START_LIFE_QUEEN', 100);       // VIE DE DEPART DE LA RENNE ABEILLE
	define('START_LIFE_WORKER', 75);       // VIE DE DEPART DES ABEILLES TRAVAILLEUSE
	define('START_LIFE_DRONE', 50);        // VIE DE DEPART DES ABEILLES DRONE

	define('REMOVE_LIFE_QUEEN', 8);        // VIE A RETIRER QUAND LA RENNE EST ATTAQUE
	define('REMOVE_LIFE_WORKER', 10);      // VIE A RETIRER QUAND LES TRAVAILLEUSES SONT ATTAQUE
	define('REMOVE_LIFE_DRONE', 12);       // VIE A RETIRER QUAND LES DRONES SONT ATTAQUE

	define('NBR_QUEEN', 1);                // NOMBRE DE RENNE DANS LA PARTIE
	define('NBR_WORKER', 5);			   // NOMBRE DE TRAVAILLEUSE DANS LA PARTIE
	define('NBR_DRONE', 8);				   // NOMBRE DE DRONE DANS LA PARTIE
	
?>